# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Fetch source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: Caranouga/FlowBoard
          ref: master
      - name: Update labels
        uses: actions/labeler@v5
        with:
          sync-labels: true
          dot: true
